// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: stats.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createStat = `-- name: CreateStat :one
INSERT INTO stats (id, created_at, updated_at, score)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, score
`

type CreateStatParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Score     int32
}

func (q *Queries) CreateStat(ctx context.Context, arg CreateStatParams) (Stat, error) {
	row := q.db.QueryRowContext(ctx, createStat,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Score,
	)
	var i Stat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Score,
	)
	return i, err
}
