services:
  postgres:
    image: postgres:16.3
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: flash
      POSTGRES_PASSWORD: flashpw
      POSTGRES_DB: flashdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
